### PR TITLE
Updates of API Definition 2.0 for #24 and #100

### PR DESCRIPTION
**Pull request by ehenrka**
This PR should contain the required changes for issues #24 and #100.

### CODE REVIEW

**Review by lewisdaly — DISMISSED** [review]
Looks good to me @ehenrka. It's a shame you had to add the table at the start of the document!

**Review by elnyry-sam-k — DISMISSED** [review]

**Comment by elnyry-sam-k** [comment]
Thanks @ehenrka; the PR shows some conflicts that needs to be resolved but otherwise the changes look good..

**Comment by ehenrka** [comment]
Conflict should be fixed now (was due to the table fix from yesterday).

**Review by elnyry-sam-k — APPROVED** [review]
Thanks Henrik; please continue with merging..

**Pull request merged**
